name: Simple Stats

on:
  schedule:
    - cron: "30 6 * * *"   # Daily at 06:30 UTC
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: simple-stats
  cancel-in-progress: false

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch & generate simple stats
        env:
          GH_TOKEN: ${{ secrets.GH_SIMPLE_STATS }}
          USERNAME: tlecocq99
        run: |
          set -euo pipefail

          # Ensure jq is present (usually is)
          if ! command -v jq >/dev/null 2>&1; then
            sudo apt-get update && sudo apt-get install -y jq
          fi

          # GraphQL query
          read -r -d '' QUERY <<'EOF'
          {
            user(login: "USERNAME_PLACEHOLDER") {
              repositories(privacy: PUBLIC, ownerAffiliations: OWNER) {
                totalCount
              }
              contributionsCollection {
                contributionCalendar {
                  totalContributions
                }
              }
            }
          }
          EOF
          QUERY="${QUERY//USERNAME_PLACEHOLDER/$USERNAME}"

          RESPONSE=$(curl -s -H "Authorization: bearer $GH_TOKEN" \
            -X POST -d "{\"query\":\"${QUERY//$'\n'/ }\"}" https://api.github.com/graphql)

          if echo "$RESPONSE" | grep -q '"errors"'; then
            echo "GraphQL error in response:"
            echo "$RESPONSE"
            exit 1
          fi

          TOTAL_CONTRIB=$(echo "$RESPONSE" | jq -r '.data.user.contributionsCollection.contributionCalendar.totalContributions')
          TOTAL_PUBLIC_REPOS=$(echo "$RESPONSE" | jq -r '.data.user.repositories.totalCount')

          cat > simple-stats.md <<EOF
**Quick Stats (Auto‑Updated)**  
Public Repos: ${TOTAL_PUBLIC_REPOS} • Last 12 Months Contributions: ${TOTAL_CONTRIB}  
_Last updated: $(date -u +"%Y-%m-%d %H:%M UTC")_
EOF

          if git diff --quiet simple-stats.md 2>/dev/null; then
            echo "No changes detected; skipping commit."
          else
            git config user.name "github-actions"
            git config user.email "actions@users.noreply.github.com"
            git add simple-stats.md
            git commit -m "chore: update simple stats"
            git push
          fi
